services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BreadcrumbsBundle\Service\BreadcrumbsService:
    public: true
    arguments:
      $options: "%breadcrumbs%"

  BreadcrumbsBundle\Twig\:
    resource: '../../Twig'
    public: true
    tags:
      - { name: twig.extension }